name: dms_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UI / utils
  image_picker: ^1.1.2
  mobile_scanner: ^7.1.2
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.7.0
  app_links: ^6.3.2
  shared_preferences: ^2.3.2
  crypto: ^3.0.3
  share_plus: ^12.0.1
  firebase_app_check: ^0.3.2+10
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.4
  path: ^1.9.0
  image: ^4.2.0
  crop_your_image: ^1.1.0
  file_picker: ^8.1.2
  image_gallery_saver_plus: ^4.0.1
  http: ^1.2.2
  uuid: ^4.4.2
  google_places_flutter: ^2.0.6
  intl: ^0.19.0




  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.0
  cloud_functions: ^5.0.0
  firebase_messaging: ^15.2.10


  # Social login
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
